/********************************************************************************
** Form generated from reading UI file 'enter_wifi_password.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ENTER_WIFI_PASSWORD_H
#define UI_ENTER_WIFI_PASSWORD_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_enter_wifi_password
{
public:
    QLabel *label;
    QLabel *label_2;
    QLineEdit *ssid_textbox;
    QLineEdit *password_textbox;
    QPushButton *number_button;
    QPushButton *space_button;
    QPushButton *del_button;
    QPushButton *symbol_button;
    QGroupBox *abc_groupbox;
    QPushButton *pushButton_3;
    QPushButton *pushButton_9;
    QPushButton *pushButton_4;
    QPushButton *pushButton_10;
    QPushButton *pushButton_17;
    QPushButton *pushButton_14;
    QPushButton *pushButton_23;
    QPushButton *pushButton_6;
    QPushButton *pushButton_2;
    QPushButton *pushButton_24;
    QPushButton *pushButton_13;
    QPushButton *pushButton_11;
    QPushButton *pushButton_7;
    QPushButton *pushButton_25;
    QPushButton *pushButton_22;
    QPushButton *pushButton_21;
    QPushButton *pushButton_26;
    QPushButton *pushButton_12;
    QPushButton *pushButton_18;
    QPushButton *pushButton_15;
    QPushButton *pushButton_5;
    QPushButton *pushButton_8;
    QPushButton *pushButton_20;
    QPushButton *pushButton_16;
    QPushButton *pushButton_135;
    QPushButton *pushButton_19;
    QGroupBox *number_groupbox;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QPushButton *pushButton_66;
    QPushButton *pushButton_67;
    QPushButton *pushButton_68;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QPushButton *pushButton_72;
    QPushButton *pushButton_73;
    QPushButton *pushButton_75;
    QPushButton *pushButton_76;
    QPushButton *pushButton_77;
    QPushButton *pushButton_78;
    QPushButton *pushButton_79;
    QPushButton *pushButton_80;
    QPushButton *pushButton_81;
    QPushButton *pushButton_82;
    QPushButton *pushButton_83;
    QPushButton *pushButton_84;
    QPushButton *pushButton_85;
    QPushButton *pushButton_86;
    QPushButton *abc_button;
    QPushButton *ABC_button;
    QGroupBox *symbol_groupbox;
    QPushButton *pushButton_111;
    QPushButton *pushButton_112;
    QPushButton *pushButton_113;
    QPushButton *pushButton_114;
    QPushButton *pushButton_115;
    QPushButton *pushButton_118;
    QPushButton *pushButton_119;
    QPushButton *pushButton_120;
    QPushButton *pushButton_121;
    QPushButton *pushButton_122;
    QPushButton *pushButton_126;
    QPushButton *pushButton_127;
    QPushButton *pushButton_128;
    QPushButton *pushButton_129;
    QPushButton *pushButton_130;
    QPushButton *pushButton_131;
    QPushButton *pushButton_132;
    QPushButton *pushButton_133;
    QPushButton *pushButton_134;
    QPushButton *ok_button;
    QPushButton *cancel_button;
    QGroupBox *ABC_groupbox;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;

    void setupUi(QDialog *enter_wifi_password)
    {
        if (enter_wifi_password->objectName().isEmpty())
            enter_wifi_password->setObjectName(QString::fromUtf8("enter_wifi_password"));
        enter_wifi_password->resize(800, 480);
        label = new QLabel(enter_wifi_password);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(230, 40, 121, 16));
        QFont font;
        font.setPointSize(10);
        label->setFont(font);
        label_2 = new QLabel(enter_wifi_password);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(230, 80, 121, 16));
        label_2->setFont(font);
        ssid_textbox = new QLineEdit(enter_wifi_password);
        ssid_textbox->setObjectName(QString::fromUtf8("ssid_textbox"));
        ssid_textbox->setGeometry(QRect(330, 40, 201, 22));
        ssid_textbox->setReadOnly(true);
        password_textbox = new QLineEdit(enter_wifi_password);
        password_textbox->setObjectName(QString::fromUtf8("password_textbox"));
        password_textbox->setGeometry(QRect(330, 80, 201, 22));
        password_textbox->setEchoMode(QLineEdit::Password);
        number_button = new QPushButton(enter_wifi_password);
        number_button->setObjectName(QString::fromUtf8("number_button"));
        number_button->setGeometry(QRect(270, 320, 71, 40));
        space_button = new QPushButton(enter_wifi_password);
        space_button->setObjectName(QString::fromUtf8("space_button"));
        space_button->setGeometry(QRect(430, 320, 201, 40));
        del_button = new QPushButton(enter_wifi_password);
        del_button->setObjectName(QString::fromUtf8("del_button"));
        del_button->setGeometry(QRect(640, 320, 71, 40));
        symbol_button = new QPushButton(enter_wifi_password);
        symbol_button->setObjectName(QString::fromUtf8("symbol_button"));
        symbol_button->setGeometry(QRect(350, 320, 71, 40));
        abc_groupbox = new QGroupBox(enter_wifi_password);
        abc_groupbox->setObjectName(QString::fromUtf8("abc_groupbox"));
        abc_groupbox->setGeometry(QRect(90, 160, 621, 140));
        pushButton_3 = new QPushButton(abc_groupbox);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(130, 10, 60, 40));
        pushButton_9 = new QPushButton(abc_groupbox);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(490, 10, 60, 40));
        pushButton_4 = new QPushButton(abc_groupbox);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(190, 10, 60, 40));
        pushButton_10 = new QPushButton(abc_groupbox);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(550, 10, 60, 40));
        pushButton_17 = new QPushButton(abc_groupbox);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(390, 50, 60, 40));
        pushButton_14 = new QPushButton(abc_groupbox);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(150, 90, 60, 40));
        pushButton_23 = new QPushButton(abc_groupbox);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(90, 90, 60, 40));
        pushButton_6 = new QPushButton(abc_groupbox);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(310, 10, 60, 40));
        pushButton_2 = new QPushButton(abc_groupbox);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(70, 10, 60, 40));
        pushButton_24 = new QPushButton(abc_groupbox);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(390, 90, 60, 40));
        pushButton_13 = new QPushButton(abc_groupbox);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(270, 50, 60, 40));
        pushButton_11 = new QPushButton(abc_groupbox);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(150, 50, 60, 40));
        pushButton_7 = new QPushButton(abc_groupbox);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(370, 10, 60, 40));
        pushButton_25 = new QPushButton(abc_groupbox);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(270, 90, 60, 40));
        pushButton_22 = new QPushButton(abc_groupbox);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(450, 90, 60, 40));
        pushButton_21 = new QPushButton(abc_groupbox);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(330, 90, 60, 40));
        pushButton_26 = new QPushButton(abc_groupbox);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(210, 90, 60, 40));
        pushButton_12 = new QPushButton(abc_groupbox);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(210, 50, 60, 40));
        pushButton_18 = new QPushButton(abc_groupbox);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(90, 50, 60, 40));
        pushButton_15 = new QPushButton(abc_groupbox);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(30, 50, 60, 40));
        pushButton_5 = new QPushButton(abc_groupbox);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(250, 10, 60, 40));
        pushButton_8 = new QPushButton(abc_groupbox);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(430, 10, 60, 40));
        pushButton_20 = new QPushButton(abc_groupbox);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(510, 50, 60, 40));
        pushButton_16 = new QPushButton(abc_groupbox);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(330, 50, 60, 40));
        pushButton_135 = new QPushButton(abc_groupbox);
        pushButton_135->setObjectName(QString::fromUtf8("pushButton_135"));
        pushButton_135->setGeometry(QRect(10, 10, 60, 40));
        pushButton_19 = new QPushButton(abc_groupbox);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(450, 50, 60, 40));
        number_groupbox = new QGroupBox(enter_wifi_password);
        number_groupbox->setObjectName(QString::fromUtf8("number_groupbox"));
        number_groupbox->setGeometry(QRect(90, 160, 621, 140));
        pushButton_60 = new QPushButton(number_groupbox);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(130, 10, 60, 40));
        pushButton_61 = new QPushButton(number_groupbox);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(490, 10, 60, 40));
        pushButton_62 = new QPushButton(number_groupbox);
        pushButton_62->setObjectName(QString::fromUtf8("pushButton_62"));
        pushButton_62->setGeometry(QRect(190, 10, 60, 40));
        pushButton_63 = new QPushButton(number_groupbox);
        pushButton_63->setObjectName(QString::fromUtf8("pushButton_63"));
        pushButton_63->setGeometry(QRect(550, 10, 60, 40));
        pushButton_64 = new QPushButton(number_groupbox);
        pushButton_64->setObjectName(QString::fromUtf8("pushButton_64"));
        pushButton_64->setGeometry(QRect(400, 50, 60, 40));
        pushButton_65 = new QPushButton(number_groupbox);
        pushButton_65->setObjectName(QString::fromUtf8("pushButton_65"));
        pushButton_65->setGeometry(QRect(180, 90, 60, 40));
        pushButton_66 = new QPushButton(number_groupbox);
        pushButton_66->setObjectName(QString::fromUtf8("pushButton_66"));
        pushButton_66->setGeometry(QRect(120, 90, 60, 40));
        pushButton_67 = new QPushButton(number_groupbox);
        pushButton_67->setObjectName(QString::fromUtf8("pushButton_67"));
        pushButton_67->setGeometry(QRect(310, 10, 60, 40));
        pushButton_68 = new QPushButton(number_groupbox);
        pushButton_68->setObjectName(QString::fromUtf8("pushButton_68"));
        pushButton_68->setGeometry(QRect(70, 10, 60, 40));
        pushButton_70 = new QPushButton(number_groupbox);
        pushButton_70->setObjectName(QString::fromUtf8("pushButton_70"));
        pushButton_70->setGeometry(QRect(280, 50, 60, 40));
        pushButton_71 = new QPushButton(number_groupbox);
        pushButton_71->setObjectName(QString::fromUtf8("pushButton_71"));
        pushButton_71->setGeometry(QRect(160, 50, 60, 40));
        pushButton_72 = new QPushButton(number_groupbox);
        pushButton_72->setObjectName(QString::fromUtf8("pushButton_72"));
        pushButton_72->setGeometry(QRect(370, 10, 60, 40));
        pushButton_73 = new QPushButton(number_groupbox);
        pushButton_73->setObjectName(QString::fromUtf8("pushButton_73"));
        pushButton_73->setGeometry(QRect(300, 90, 60, 40));
        pushButton_75 = new QPushButton(number_groupbox);
        pushButton_75->setObjectName(QString::fromUtf8("pushButton_75"));
        pushButton_75->setGeometry(QRect(360, 90, 60, 40));
        pushButton_76 = new QPushButton(number_groupbox);
        pushButton_76->setObjectName(QString::fromUtf8("pushButton_76"));
        pushButton_76->setGeometry(QRect(240, 90, 60, 40));
        pushButton_77 = new QPushButton(number_groupbox);
        pushButton_77->setObjectName(QString::fromUtf8("pushButton_77"));
        pushButton_77->setGeometry(QRect(220, 50, 60, 40));
        pushButton_78 = new QPushButton(number_groupbox);
        pushButton_78->setObjectName(QString::fromUtf8("pushButton_78"));
        pushButton_78->setGeometry(QRect(100, 50, 60, 40));
        pushButton_79 = new QPushButton(number_groupbox);
        pushButton_79->setObjectName(QString::fromUtf8("pushButton_79"));
        pushButton_79->setGeometry(QRect(40, 50, 60, 40));
        pushButton_80 = new QPushButton(number_groupbox);
        pushButton_80->setObjectName(QString::fromUtf8("pushButton_80"));
        pushButton_80->setGeometry(QRect(250, 10, 60, 40));
        pushButton_81 = new QPushButton(number_groupbox);
        pushButton_81->setObjectName(QString::fromUtf8("pushButton_81"));
        pushButton_81->setGeometry(QRect(430, 10, 60, 40));
        pushButton_82 = new QPushButton(number_groupbox);
        pushButton_82->setObjectName(QString::fromUtf8("pushButton_82"));
        pushButton_82->setGeometry(QRect(520, 50, 60, 40));
        pushButton_83 = new QPushButton(number_groupbox);
        pushButton_83->setObjectName(QString::fromUtf8("pushButton_83"));
        pushButton_83->setGeometry(QRect(340, 50, 60, 40));
        pushButton_84 = new QPushButton(number_groupbox);
        pushButton_84->setObjectName(QString::fromUtf8("pushButton_84"));
        pushButton_84->setGeometry(QRect(10, 10, 60, 40));
        pushButton_85 = new QPushButton(number_groupbox);
        pushButton_85->setObjectName(QString::fromUtf8("pushButton_85"));
        pushButton_85->setGeometry(QRect(460, 50, 60, 40));
        pushButton_86 = new QPushButton(number_groupbox);
        pushButton_86->setObjectName(QString::fromUtf8("pushButton_86"));
        pushButton_86->setGeometry(QRect(420, 90, 60, 40));
        abc_button = new QPushButton(enter_wifi_password);
        abc_button->setObjectName(QString::fromUtf8("abc_button"));
        abc_button->setGeometry(QRect(110, 320, 71, 40));
        ABC_button = new QPushButton(enter_wifi_password);
        ABC_button->setObjectName(QString::fromUtf8("ABC_button"));
        ABC_button->setGeometry(QRect(190, 320, 71, 40));
        symbol_groupbox = new QGroupBox(enter_wifi_password);
        symbol_groupbox->setObjectName(QString::fromUtf8("symbol_groupbox"));
        symbol_groupbox->setGeometry(QRect(90, 160, 621, 140));
        pushButton_111 = new QPushButton(symbol_groupbox);
        pushButton_111->setObjectName(QString::fromUtf8("pushButton_111"));
        pushButton_111->setGeometry(QRect(130, 10, 60, 40));
        pushButton_112 = new QPushButton(symbol_groupbox);
        pushButton_112->setObjectName(QString::fromUtf8("pushButton_112"));
        pushButton_112->setGeometry(QRect(490, 10, 60, 40));
        pushButton_113 = new QPushButton(symbol_groupbox);
        pushButton_113->setObjectName(QString::fromUtf8("pushButton_113"));
        pushButton_113->setGeometry(QRect(190, 10, 60, 40));
        pushButton_114 = new QPushButton(symbol_groupbox);
        pushButton_114->setObjectName(QString::fromUtf8("pushButton_114"));
        pushButton_114->setGeometry(QRect(550, 10, 60, 40));
        pushButton_115 = new QPushButton(symbol_groupbox);
        pushButton_115->setObjectName(QString::fromUtf8("pushButton_115"));
        pushButton_115->setGeometry(QRect(400, 50, 60, 40));
        pushButton_118 = new QPushButton(symbol_groupbox);
        pushButton_118->setObjectName(QString::fromUtf8("pushButton_118"));
        pushButton_118->setGeometry(QRect(310, 10, 60, 40));
        pushButton_119 = new QPushButton(symbol_groupbox);
        pushButton_119->setObjectName(QString::fromUtf8("pushButton_119"));
        pushButton_119->setGeometry(QRect(70, 10, 60, 40));
        pushButton_120 = new QPushButton(symbol_groupbox);
        pushButton_120->setObjectName(QString::fromUtf8("pushButton_120"));
        pushButton_120->setGeometry(QRect(280, 50, 60, 40));
        pushButton_121 = new QPushButton(symbol_groupbox);
        pushButton_121->setObjectName(QString::fromUtf8("pushButton_121"));
        pushButton_121->setGeometry(QRect(160, 50, 60, 40));
        pushButton_122 = new QPushButton(symbol_groupbox);
        pushButton_122->setObjectName(QString::fromUtf8("pushButton_122"));
        pushButton_122->setGeometry(QRect(370, 10, 60, 40));
        pushButton_126 = new QPushButton(symbol_groupbox);
        pushButton_126->setObjectName(QString::fromUtf8("pushButton_126"));
        pushButton_126->setGeometry(QRect(220, 50, 60, 40));
        pushButton_127 = new QPushButton(symbol_groupbox);
        pushButton_127->setObjectName(QString::fromUtf8("pushButton_127"));
        pushButton_127->setGeometry(QRect(100, 50, 60, 40));
        pushButton_128 = new QPushButton(symbol_groupbox);
        pushButton_128->setObjectName(QString::fromUtf8("pushButton_128"));
        pushButton_128->setGeometry(QRect(40, 50, 60, 40));
        pushButton_129 = new QPushButton(symbol_groupbox);
        pushButton_129->setObjectName(QString::fromUtf8("pushButton_129"));
        pushButton_129->setGeometry(QRect(250, 10, 60, 40));
        pushButton_130 = new QPushButton(symbol_groupbox);
        pushButton_130->setObjectName(QString::fromUtf8("pushButton_130"));
        pushButton_130->setGeometry(QRect(430, 10, 60, 40));
        pushButton_131 = new QPushButton(symbol_groupbox);
        pushButton_131->setObjectName(QString::fromUtf8("pushButton_131"));
        pushButton_131->setGeometry(QRect(520, 50, 60, 40));
        pushButton_132 = new QPushButton(symbol_groupbox);
        pushButton_132->setObjectName(QString::fromUtf8("pushButton_132"));
        pushButton_132->setGeometry(QRect(340, 50, 60, 40));
        pushButton_133 = new QPushButton(symbol_groupbox);
        pushButton_133->setObjectName(QString::fromUtf8("pushButton_133"));
        pushButton_133->setGeometry(QRect(10, 10, 60, 40));
        pushButton_134 = new QPushButton(symbol_groupbox);
        pushButton_134->setObjectName(QString::fromUtf8("pushButton_134"));
        pushButton_134->setGeometry(QRect(460, 50, 60, 40));
        ok_button = new QPushButton(enter_wifi_password);
        ok_button->setObjectName(QString::fromUtf8("ok_button"));
        ok_button->setGeometry(QRect(520, 380, 93, 28));
        cancel_button = new QPushButton(enter_wifi_password);
        cancel_button->setObjectName(QString::fromUtf8("cancel_button"));
        cancel_button->setGeometry(QRect(620, 380, 93, 28));
        ABC_groupbox = new QGroupBox(enter_wifi_password);
        ABC_groupbox->setObjectName(QString::fromUtf8("ABC_groupbox"));
        ABC_groupbox->setGeometry(QRect(90, 160, 621, 140));
        pushButton_27 = new QPushButton(ABC_groupbox);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(130, 10, 60, 40));
        pushButton_28 = new QPushButton(ABC_groupbox);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(490, 10, 60, 40));
        pushButton_29 = new QPushButton(ABC_groupbox);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(190, 10, 60, 40));
        pushButton_30 = new QPushButton(ABC_groupbox);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(550, 10, 60, 40));
        pushButton_31 = new QPushButton(ABC_groupbox);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(390, 50, 60, 40));
        pushButton_32 = new QPushButton(ABC_groupbox);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(150, 90, 60, 40));
        pushButton_33 = new QPushButton(ABC_groupbox);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(90, 90, 60, 40));
        pushButton_34 = new QPushButton(ABC_groupbox);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(310, 10, 60, 40));
        pushButton_35 = new QPushButton(ABC_groupbox);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(70, 10, 60, 40));
        pushButton_36 = new QPushButton(ABC_groupbox);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(390, 90, 60, 40));
        pushButton_37 = new QPushButton(ABC_groupbox);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(270, 50, 60, 40));
        pushButton_38 = new QPushButton(ABC_groupbox);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(150, 50, 60, 40));
        pushButton_39 = new QPushButton(ABC_groupbox);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(370, 10, 60, 40));
        pushButton_40 = new QPushButton(ABC_groupbox);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(270, 90, 60, 40));
        pushButton_41 = new QPushButton(ABC_groupbox);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(450, 90, 60, 40));
        pushButton_42 = new QPushButton(ABC_groupbox);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(330, 90, 60, 40));
        pushButton_43 = new QPushButton(ABC_groupbox);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(210, 90, 60, 40));
        pushButton_44 = new QPushButton(ABC_groupbox);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(210, 50, 60, 40));
        pushButton_45 = new QPushButton(ABC_groupbox);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(90, 50, 60, 40));
        pushButton_46 = new QPushButton(ABC_groupbox);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(30, 50, 60, 40));
        pushButton_47 = new QPushButton(ABC_groupbox);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(250, 10, 60, 40));
        pushButton_48 = new QPushButton(ABC_groupbox);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(430, 10, 60, 40));
        pushButton_49 = new QPushButton(ABC_groupbox);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(510, 50, 60, 40));
        pushButton_50 = new QPushButton(ABC_groupbox);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(330, 50, 60, 40));
        pushButton_51 = new QPushButton(ABC_groupbox);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(10, 10, 60, 40));
        pushButton_51->setStyleSheet(QString::fromUtf8(""));
        pushButton_52 = new QPushButton(ABC_groupbox);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(450, 50, 60, 40));
        number_groupbox->raise();
        symbol_groupbox->raise();
        label->raise();
        label_2->raise();
        ssid_textbox->raise();
        password_textbox->raise();
        number_button->raise();
        space_button->raise();
        del_button->raise();
        symbol_button->raise();
        abc_groupbox->raise();
        abc_button->raise();
        ABC_button->raise();
        ok_button->raise();
        cancel_button->raise();
        ABC_groupbox->raise();

        retranslateUi(enter_wifi_password);

        QMetaObject::connectSlotsByName(enter_wifi_password);
    } // setupUi

    void retranslateUi(QDialog *enter_wifi_password)
    {
        enter_wifi_password->setWindowTitle(QApplication::translate("enter_wifi_password", "Dialog", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("enter_wifi_password", "SSID", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("enter_wifi_password", "Password", 0, QApplication::UnicodeUTF8));
        number_button->setText(QApplication::translate("enter_wifi_password", "123", 0, QApplication::UnicodeUTF8));
        space_button->setText(QApplication::translate("enter_wifi_password", "space", 0, QApplication::UnicodeUTF8));
        del_button->setText(QApplication::translate("enter_wifi_password", "DEL", 0, QApplication::UnicodeUTF8));
        symbol_button->setText(QApplication::translate("enter_wifi_password", "#+=", 0, QApplication::UnicodeUTF8));
        abc_groupbox->setTitle(QString());
        pushButton_3->setText(QApplication::translate("enter_wifi_password", "e", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("enter_wifi_password", "o", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("enter_wifi_password", "r", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("enter_wifi_password", "p", 0, QApplication::UnicodeUTF8));
        pushButton_17->setText(QApplication::translate("enter_wifi_password", "j", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("enter_wifi_password", "x", 0, QApplication::UnicodeUTF8));
        pushButton_23->setText(QApplication::translate("enter_wifi_password", "z", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("enter_wifi_password", "y", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("enter_wifi_password", "w", 0, QApplication::UnicodeUTF8));
        pushButton_24->setText(QApplication::translate("enter_wifi_password", "n", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("enter_wifi_password", "g", 0, QApplication::UnicodeUTF8));
        pushButton_11->setText(QApplication::translate("enter_wifi_password", "d", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("enter_wifi_password", "u", 0, QApplication::UnicodeUTF8));
        pushButton_25->setText(QApplication::translate("enter_wifi_password", "v", 0, QApplication::UnicodeUTF8));
        pushButton_22->setText(QApplication::translate("enter_wifi_password", "m", 0, QApplication::UnicodeUTF8));
        pushButton_21->setText(QApplication::translate("enter_wifi_password", "b", 0, QApplication::UnicodeUTF8));
        pushButton_26->setText(QApplication::translate("enter_wifi_password", "c", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("enter_wifi_password", "f", 0, QApplication::UnicodeUTF8));
        pushButton_18->setText(QApplication::translate("enter_wifi_password", "s", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("enter_wifi_password", "a", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("enter_wifi_password", "t", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("enter_wifi_password", "i", 0, QApplication::UnicodeUTF8));
        pushButton_20->setText(QApplication::translate("enter_wifi_password", "l", 0, QApplication::UnicodeUTF8));
        pushButton_16->setText(QApplication::translate("enter_wifi_password", "h", 0, QApplication::UnicodeUTF8));
        pushButton_135->setText(QApplication::translate("enter_wifi_password", "q", 0, QApplication::UnicodeUTF8));
        pushButton_19->setText(QApplication::translate("enter_wifi_password", "k", 0, QApplication::UnicodeUTF8));
        number_groupbox->setTitle(QApplication::translate("enter_wifi_password", ",", 0, QApplication::UnicodeUTF8));
        pushButton_60->setText(QApplication::translate("enter_wifi_password", "3", 0, QApplication::UnicodeUTF8));
        pushButton_61->setText(QApplication::translate("enter_wifi_password", "9", 0, QApplication::UnicodeUTF8));
        pushButton_62->setText(QApplication::translate("enter_wifi_password", "4", 0, QApplication::UnicodeUTF8));
        pushButton_63->setText(QApplication::translate("enter_wifi_password", "0", 0, QApplication::UnicodeUTF8));
        pushButton_64->setText(QApplication::translate("enter_wifi_password", "$", 0, QApplication::UnicodeUTF8));
        pushButton_65->setText(QApplication::translate("enter_wifi_password", ",", 0, QApplication::UnicodeUTF8));
        pushButton_66->setText(QApplication::translate("enter_wifi_password", ".", 0, QApplication::UnicodeUTF8));
        pushButton_67->setText(QApplication::translate("enter_wifi_password", "6", 0, QApplication::UnicodeUTF8));
        pushButton_68->setText(QApplication::translate("enter_wifi_password", "2", 0, QApplication::UnicodeUTF8));
        pushButton_70->setText(QApplication::translate("enter_wifi_password", "(", 0, QApplication::UnicodeUTF8));
        pushButton_71->setText(QApplication::translate("enter_wifi_password", ":", 0, QApplication::UnicodeUTF8));
        pushButton_72->setText(QApplication::translate("enter_wifi_password", "7", 0, QApplication::UnicodeUTF8));
        pushButton_73->setText(QApplication::translate("enter_wifi_password", "!", 0, QApplication::UnicodeUTF8));
        pushButton_75->setText(QApplication::translate("enter_wifi_password", "'", 0, QApplication::UnicodeUTF8));
        pushButton_76->setText(QApplication::translate("enter_wifi_password", "?", 0, QApplication::UnicodeUTF8));
        pushButton_77->setText(QApplication::translate("enter_wifi_password", ";", 0, QApplication::UnicodeUTF8));
        pushButton_78->setText(QApplication::translate("enter_wifi_password", "/", 0, QApplication::UnicodeUTF8));
        pushButton_79->setText(QApplication::translate("enter_wifi_password", "-", 0, QApplication::UnicodeUTF8));
        pushButton_80->setText(QApplication::translate("enter_wifi_password", "5", 0, QApplication::UnicodeUTF8));
        pushButton_81->setText(QApplication::translate("enter_wifi_password", "8", 0, QApplication::UnicodeUTF8));
        pushButton_82->setText(QApplication::translate("enter_wifi_password", "@", 0, QApplication::UnicodeUTF8));
        pushButton_83->setText(QApplication::translate("enter_wifi_password", ")", 0, QApplication::UnicodeUTF8));
        pushButton_84->setText(QApplication::translate("enter_wifi_password", "1", 0, QApplication::UnicodeUTF8));
        pushButton_85->setText(QApplication::translate("enter_wifi_password", "&&", 0, QApplication::UnicodeUTF8));
        pushButton_86->setText(QApplication::translate("enter_wifi_password", "\"", 0, QApplication::UnicodeUTF8));
        abc_button->setText(QApplication::translate("enter_wifi_password", "abc", 0, QApplication::UnicodeUTF8));
        ABC_button->setText(QApplication::translate("enter_wifi_password", "ABC", 0, QApplication::UnicodeUTF8));
        symbol_groupbox->setTitle(QApplication::translate("enter_wifi_password", ",", 0, QApplication::UnicodeUTF8));
        pushButton_111->setText(QApplication::translate("enter_wifi_password", "{", 0, QApplication::UnicodeUTF8));
        pushButton_112->setText(QApplication::translate("enter_wifi_password", "+", 0, QApplication::UnicodeUTF8));
        pushButton_113->setText(QApplication::translate("enter_wifi_password", "}", 0, QApplication::UnicodeUTF8));
        pushButton_114->setText(QApplication::translate("enter_wifi_password", "=", 0, QApplication::UnicodeUTF8));
        pushButton_115->setText(QApplication::translate("enter_wifi_password", "$", 0, QApplication::UnicodeUTF8));
        pushButton_118->setText(QApplication::translate("enter_wifi_password", "%", 0, QApplication::UnicodeUTF8));
        pushButton_119->setText(QApplication::translate("enter_wifi_password", "]", 0, QApplication::UnicodeUTF8));
        pushButton_120->setText(QApplication::translate("enter_wifi_password", "<", 0, QApplication::UnicodeUTF8));
        pushButton_121->setText(QApplication::translate("enter_wifi_password", "|", 0, QApplication::UnicodeUTF8));
        pushButton_122->setText(QApplication::translate("enter_wifi_password", "^", 0, QApplication::UnicodeUTF8));
        pushButton_126->setText(QApplication::translate("enter_wifi_password", "~", 0, QApplication::UnicodeUTF8));
        pushButton_127->setText(QApplication::translate("enter_wifi_password", "\\", 0, QApplication::UnicodeUTF8));
        pushButton_128->setText(QApplication::translate("enter_wifi_password", "_", 0, QApplication::UnicodeUTF8));
        pushButton_129->setText(QApplication::translate("enter_wifi_password", "#", 0, QApplication::UnicodeUTF8));
        pushButton_130->setText(QApplication::translate("enter_wifi_password", "*", 0, QApplication::UnicodeUTF8));
        pushButton_131->setText(QApplication::translate("enter_wifi_password", "@", 0, QApplication::UnicodeUTF8));
        pushButton_132->setText(QApplication::translate("enter_wifi_password", ">", 0, QApplication::UnicodeUTF8));
        pushButton_133->setText(QApplication::translate("enter_wifi_password", "[", 0, QApplication::UnicodeUTF8));
        pushButton_134->setText(QApplication::translate("enter_wifi_password", "`", 0, QApplication::UnicodeUTF8));
        ok_button->setText(QApplication::translate("enter_wifi_password", "OK", 0, QApplication::UnicodeUTF8));
        cancel_button->setText(QApplication::translate("enter_wifi_password", "Cancel", 0, QApplication::UnicodeUTF8));
        ABC_groupbox->setTitle(QString());
        pushButton_27->setText(QApplication::translate("enter_wifi_password", "E", 0, QApplication::UnicodeUTF8));
        pushButton_28->setText(QApplication::translate("enter_wifi_password", "O", 0, QApplication::UnicodeUTF8));
        pushButton_29->setText(QApplication::translate("enter_wifi_password", "R", 0, QApplication::UnicodeUTF8));
        pushButton_30->setText(QApplication::translate("enter_wifi_password", "P", 0, QApplication::UnicodeUTF8));
        pushButton_31->setText(QApplication::translate("enter_wifi_password", "J", 0, QApplication::UnicodeUTF8));
        pushButton_32->setText(QApplication::translate("enter_wifi_password", "X", 0, QApplication::UnicodeUTF8));
        pushButton_33->setText(QApplication::translate("enter_wifi_password", "Z", 0, QApplication::UnicodeUTF8));
        pushButton_34->setText(QApplication::translate("enter_wifi_password", "Y", 0, QApplication::UnicodeUTF8));
        pushButton_35->setText(QApplication::translate("enter_wifi_password", "W", 0, QApplication::UnicodeUTF8));
        pushButton_36->setText(QApplication::translate("enter_wifi_password", "N", 0, QApplication::UnicodeUTF8));
        pushButton_37->setText(QApplication::translate("enter_wifi_password", "G", 0, QApplication::UnicodeUTF8));
        pushButton_38->setText(QApplication::translate("enter_wifi_password", "D", 0, QApplication::UnicodeUTF8));
        pushButton_39->setText(QApplication::translate("enter_wifi_password", "U", 0, QApplication::UnicodeUTF8));
        pushButton_40->setText(QApplication::translate("enter_wifi_password", "V", 0, QApplication::UnicodeUTF8));
        pushButton_41->setText(QApplication::translate("enter_wifi_password", "M", 0, QApplication::UnicodeUTF8));
        pushButton_42->setText(QApplication::translate("enter_wifi_password", "B", 0, QApplication::UnicodeUTF8));
        pushButton_43->setText(QApplication::translate("enter_wifi_password", "C", 0, QApplication::UnicodeUTF8));
        pushButton_44->setText(QApplication::translate("enter_wifi_password", "F", 0, QApplication::UnicodeUTF8));
        pushButton_45->setText(QApplication::translate("enter_wifi_password", "S", 0, QApplication::UnicodeUTF8));
        pushButton_46->setText(QApplication::translate("enter_wifi_password", "A", 0, QApplication::UnicodeUTF8));
        pushButton_47->setText(QApplication::translate("enter_wifi_password", "T", 0, QApplication::UnicodeUTF8));
        pushButton_48->setText(QApplication::translate("enter_wifi_password", "I", 0, QApplication::UnicodeUTF8));
        pushButton_49->setText(QApplication::translate("enter_wifi_password", "L", 0, QApplication::UnicodeUTF8));
        pushButton_50->setText(QApplication::translate("enter_wifi_password", "H", 0, QApplication::UnicodeUTF8));
        pushButton_51->setText(QApplication::translate("enter_wifi_password", "Q", 0, QApplication::UnicodeUTF8));
        pushButton_52->setText(QApplication::translate("enter_wifi_password", "K", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class enter_wifi_password: public Ui_enter_wifi_password {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ENTER_WIFI_PASSWORD_H
